version: '2'
services:
    daspanel-caddy-http-server:
        image: daspanel/caddy-http-server
        volumes:
            - ./data:/opt/daspanel/data
        networks:
            - frontend
            - backend
        env_file:
            - daspanel.env
        ports:
            - "80:80"
            - "443:443"
networks:  
  frontend:
    driver: bridge
  backend:
    driver: bridge


