
version: '2'
services:
    daspanel-caddy-http-server:
        build:
            context: .
            dockerfile: Dockerfile
        image: daspanel/caddy-http-server
        volumes:
            - daspanel-data:/opt/daspanel/data
        networks:
            - frontend
            - backend
        env_file:
            - daspanel.env
        ports:
            - "80:80"
            - "443:443"

volumes:
    daspanel-data:
        external:
            name: daspanel-data

networks:  
  frontend:
    driver: bridge
  backend:
    driver: bridge


