#!/usr/bin/with-contenv sh

# Installation UUID must be informed
if [ -z "$DASPANEL_SYS_UUID" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
    echo "***"
    exit 1
fi

export DASPANEL_SYS_HOSTNAME=`cat /opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json | /usr/bin/jq -r '.sys.hostname'`

log() {
  if [[ "$@" ]]; then echo "[`date +'%Y-%m-%d %T'`] $@";
  else echo; fi
}

if [ ! -d "/opt/daspanel/log/$DASPANEL_SYS_UUID/caddy" ]; then
	mkdir -p /opt/daspanel/log/$DASPANEL_SYS_UUID/caddy
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/content/_default" ]; then
	mkdir -p /opt/daspanel/data/$DASPANEL_SYS_UUID/content/_default
fi

if [ ! -f "/opt/daspanel/data/$DASPANEL_SYS_UUID/content/_default/index.html" ]; then
  cp /opt/daspanel/default/caddy/content/index.html /opt/daspanel/data/$DASPANEL_SYS_UUID/content/_default/index.html
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/conf/caddy/etc/caddy/sites-available" ]; then
    mkdir -p /opt/daspanel/data/$DASPANEL_SYS_UUID/conf/caddy/etc/caddy/sites-available
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/conf/caddy/etc/caddy/sites-enabled" ]; then
    mkdir -p /opt/daspanel/data/$DASPANEL_SYS_UUID/conf/caddy/etc/caddy/sites-enabled
fi

if [ -d "/etc/caddy/sites-available" ]; then
    rm -Rf /etc/caddy/sites-available
fi

if [ -d "/etc/caddy/sites-enabled" ]; then
    rm -Rf /etc/caddy/sites-enabled
fi

ln -sf /opt/daspanel/data/$DASPANEL_SYS_UUID/conf/caddy/etc/caddy/sites-available /etc/caddy/sites-available
ln -sf /opt/daspanel/data/$DASPANEL_SYS_UUID/conf/caddy/etc/caddy/sites-enabled /etc/caddy/sites-enabled

# Configure caddy
/usr/bin/gomplate -d cfg=file:///opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json \
  < /opt/daspanel/conf-templates/etc/caddy/caddyfile.tmpl \
  > /etc/caddy/caddyfile

# secure daspanel
chown -R daspanel:daspanel /opt/daspanel/data
chown -R daspanel:daspanel /opt/daspanel/log

